# image:linux distribution
FROM node:alpine
# copy the current directory to /app
COPY . /app
# set the working directory to /app
WORKDIR /app
CMD node app.js

# to package the app into a docker image
# docker build -t hello-world .
# to list the images
# docker images
# to run the image
# docker run hello-world